export const catalog = [
  ["accordion", "Accordion", "Conteúdo expansível com navegação por teclado.", "Interação"],
  ["alert", "Alert", "Avisos de informação, sucesso e erro.", "Feedback"],
  ["alert-dialog", "Alert Dialog", "Confirmações com foco e ações explícitas.", "Sobreposições"],
  ["aspect-ratio", "Aspect Ratio", "Proporção consistente para imagens e vídeos.", "Layout"],
  ["attachment", "Attachment", "Seleção e apresentação de arquivos anexados.", "Formulários"],
  ["avatar", "Avatar", "Imagem de perfil com fallback.", "Conteúdo"],
  ["badge", "Badge", "Etiquetas compactas para estados e categorias.", "Conteúdo"],
  ["breadcrumb", "Breadcrumb", "Hierarquia de navegação em páginas.", "Navegação"],
  ["bubble", "Bubble", "Balões de conversa com conteúdo e metadados.", "Mensagens"],
  ["button", "Button", "Ações com variantes e tamanhos.", "Interação"],
  ["button-group", "Button Group", "Agrupamento de ações relacionadas.", "Interação"],
  ["calendar", "Calendar", "Seleção de datas e navegação entre meses.", "Formulários"],
  ["card", "Card", "Blocos de conteúdo com cabeçalho e rodapé.", "Conteúdo"],
  ["carousel", "Carousel", "Sequência de slides com controles e teclado.", "Interação"],
  ["chart", "Chart", "Gráficos responsivos para visualizar dados.", "Dados"],
  ["checkbox", "Checkbox", "Seleção independente com estado intermediário.", "Formulários"],
  ["collapsible", "Collapsible", "Expansão de conteúdo complementar.", "Interação"],
  ["combobox", "Combobox", "Seleção de opções com busca.", "Formulários"],
  ["command", "Command", "Paleta de comandos filtrável.", "Navegação"],
  ["context-menu", "Context Menu", "Ações disponíveis pelo menu de contexto.", "Sobreposições"],
  ["data-table", "Data Table", "Tabela com busca, ordenação e paginação.", "Dados"],
  ["date-picker", "Date Picker", "Campo de data com calendário flutuante.", "Formulários"],
  ["dialog", "Dialog", "Modal acessível para tarefas focadas.", "Sobreposições"],
  ["direction", "Direction", "Direção de leitura LTR e RTL.", "Layout"],
  ["drawer", "Drawer", "Painel que abre a partir de uma borda.", "Sobreposições"],
  ["dropdown-menu", "Dropdown Menu", "Menu de ações a partir de um botão.", "Sobreposições"],
  ["empty", "Empty", "Estados vazios com contexto e uma próxima ação.", "Conteúdo"],
  ["field", "Field", "Campos com rótulos, ajuda e erros.", "Formulários"],
  ["hover-card", "Hover Card", "Prévia contextual ao passar ou focar.", "Sobreposições"],
  ["input", "Input", "Entrada de texto com estados de foco e desabilitado.", "Formulários"],
  ["input-group", "Input Group", "Campos com prefixos, sufixos e ações.", "Formulários"],
  ["input-otp", "Input OTP", "Entrada de códigos de verificação.", "Formulários"],
  ["item", "Item", "Itens compostos para listas de conteúdo.", "Conteúdo"],
  ["kbd", "Kbd", "Representação visual de atalhos de teclado.", "Conteúdo"],
  ["label", "Label", "Rótulos associados aos controles.", "Formulários"],
  ["marker", "Marker", "Destaques de texto com cor e contraste.", "Conteúdo"],
  ["menubar", "Menubar", "Barra de menus com navegação por teclado.", "Navegação"],
  ["message", "Message", "Mensagens com autoria, conteúdo e ações.", "Mensagens"],
  ["message-scroller", "Message Scroller", "Histórico com acompanhamento de novas mensagens.", "Mensagens"],
  ["native-select", "Native Select", "Seleção com o controle nativo do navegador.", "Formulários"],
  ["navigation-menu", "Navigation Menu", "Navegação principal com conteúdo expansível.", "Navegação"],
  ["pagination", "Pagination", "Controles para percorrer páginas de resultados.", "Navegação"],
  ["popover", "Popover", "Conteúdo contextual com posicionamento automático.", "Sobreposições"],
  ["progress", "Progress", "Progresso de uma operação.", "Feedback"],
  ["questionnaire", "Questionnaire", "Questionário em etapas com respostas e conclusão.", "Formulários"],
  ["radio-group", "Radio Group", "Seleção exclusiva entre opções.", "Formulários"],
  ["resizable", "Resizable", "Painéis cujo tamanho pode ser ajustado.", "Layout"],
  ["scroll-area", "Scroll Area", "Área rolável com barras personalizadas.", "Layout"],
  ["search", "Search", "Busca com atalho e ação para limpar.", "Formulários"],
  ["select", "Select", "Lista de seleção acessível com teclado.", "Formulários"],
  ["separator", "Separator", "Divisores horizontais e verticais.", "Layout"],
  ["sheet", "Sheet", "Painel lateral para conteúdo complementar.", "Sobreposições"],
  ["sidebar", "Sidebar", "Navegação lateral com versão móvel.", "Navegação"],
  ["skeleton", "Skeleton", "Estrutura visual durante o carregamento.", "Feedback"],
  ["slider", "Slider", "Ajuste de valores em um intervalo.", "Formulários"],
  ["spinner", "Spinner", "Indicador de atividade com descrição acessível.", "Feedback"],
  ["switch", "Switch", "Alternância entre dois estados.", "Formulários"],
  ["table", "Table", "Tabela semântica com cabeçalho e legenda.", "Dados"],
  ["tabs", "Tabs", "Conteúdo organizado em abas.", "Navegação"],
  ["textarea", "Textarea", "Entrada de texto em múltiplas linhas.", "Formulários"],
  ["toast", "Toast", "Notificações temporárias com ação opcional.", "Feedback"],
  ["toggle", "Toggle", "Botão com estado pressionado.", "Interação"],
  ["toggle-group", "Toggle Group", "Conjunto de botões selecionáveis.", "Interação"],
  ["tooltip", "Tooltip", "Ajuda breve ao passar ou focar.", "Sobreposições"],
  ["typography", "Typography", "Hierarquia de títulos, parágrafos e citações.", "Conteúdo"],
];
